
import React from 'react';
import { formatDate } from '@/lib/utils';

interface ReturnRequestFooterProps {
  createdAt: string;
  createdBy?: string | null;
}

const ReturnRequestFooter: React.FC<ReturnRequestFooterProps> = ({
  createdAt,
  createdBy
}) => {
  return (
    <div className="text-xs text-center text-gray-400 mt-12 space-y-1 border-t pt-6">
      <div>This return request was generated by the Return Management System</div>
      <div>
        Created on: {formatDate(new Date(createdAt))}
      </div>
      {createdBy && (
        <div>
          Created by: {createdBy}
        </div>
      )}
    </div>
  );
};

export default ReturnRequestFooter;
