
import { format } from 'date-fns';

interface QuotationFooterProps {
  createdAt?: string;
}

export const QuotationFooter = ({ createdAt }: QuotationFooterProps) => {
  return (
    <div className="text-xs text-center text-gray-400 mt-12 space-y-1">
      <div>This quotation was generated by the Sales Management System</div>
      {createdAt && (
        <div>
          Created on: {format(new Date(createdAt), 'MMMM dd, yyyy')}
        </div>
      )}
    </div>
  );
};
